  
name: Appsody-Actions CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build-push
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
        DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO }} 
      run: |
        echo 'Docker Login...'
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_KEY
        echo 'Installing Appsody...'
        wget https://github.com/appsody/appsody/releases/download/0.5.0/appsody_0.5.0_amd64.deb
        sudo apt install -f ./appsody_0.5.0_amd64.deb
        echo 'Running Appsody build and pushing to docker registry...'
        appsody build --tag appsody-actions:v1 --push-url $DOCKER_HUB_USER
